### ISSUE TITLE
build fail on Ubuntu 18.10

### ISSUE THREAD

**Issue by thibaudk** [ossia/score-addon-sequences#1]
score commit 43951b659cd98e6d59ac2de180087271c862c5c9
on master
libossia commit 04261282b148b583b36108ec2485ea853e271780
on master

Here is the log:

`[ 94%] Building CXX object src/addons/score-addon-sequences/CMakeFiles/score_addon_sequence_unity.dir/cotire/score_addon_sequence_CXX_unity.cxx.o
In file included from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:8:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp: In member function ‘virtual void sequence::Model::setDurationAndScale(const TimeVal&)’:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp:123:41: error: ‘virtual void Process::ProcessModel::setDurationAndScale(const TimeVal&)’ is protected within this context
     proc.setDurationAndScale(newDuration);
                                         ^
In file included from /home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Execution/ProcessComponent.hpp:4,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.hpp:2,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.cpp:1,
                 from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:4:
/home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Process.hpp:142:16: note: declared protected here
   virtual void setDurationAndScale(const TimeVal& newDuration) noexcept;
                ^~~~~~~~~~~~~~~~~~~
In file included from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:8:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp: In member function ‘virtual void sequence::Model::setDurationAndGrow(const TimeVal&)’:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp:130:40: error: ‘virtual void Process::ProcessModel::setDurationAndGrow(const TimeVal&)’ is protected within this context
     proc.setDurationAndGrow(newDuration);
                                        ^
In file included from /home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Execution/ProcessComponent.hpp:4,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.hpp:2,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.cpp:1,
                 from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:4:
/home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Process.hpp:145:16: note: declared protected here
   virtual void setDurationAndGrow(const TimeVal& newDuration) noexcept;
                ^~~~~~~~~~~~~~~~~~
In file included from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:8:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp: In member function ‘virtual void sequence::Model::setDurationAndShrink(const TimeVal&)’:
/home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Process.cpp:137:42: error: ‘virtual void Process::ProcessModel::setDurationAndShrink(const TimeVal&)’ is protected within this context
     proc.setDurationAndShrink(newDuration);
                                          ^
In file included from /home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Execution/ProcessComponent.hpp:4,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.hpp:2,
                 from /home/scrime/Documents/dev/score/src/addons/score-addon-sequences/sequence/Executor.cpp:1,
                 from /home/scrime/Documents/dev/score/build/src/addons/score-addon-sequences/cotire/score_addon_sequence_CXX_unity.cxx:4:
/home/scrime/Documents/dev/score/src/plugins/score-lib-process/Process/Process.hpp:148:16: note: declared protected here
   virtual void setDurationAndShrink(const TimeVal& newDuration) noexcept;
                ^~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-four-char-constants’
make[3]: *** [src/addons/score-addon-sequences/CMakeFiles/score_addon_sequence_unity.dir/build.make:76: src/addons/score-addon-sequences/CMakeFiles/score_addon_sequence_unity.dir/cotire/score_addon_sequence_CXX_unity.cxx.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:5516: src/addons/score-addon-sequences/CMakeFiles/score_addon_sequence_unity.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1647: 3rdparty/libossia/OSSIA/CMakeFiles/all_unity.dir/rule] Error 2
make: *** [Makefile:743: all_unity] Error 2`

**Comment by jcelerier** [comment]
yep, it's unuseable for now :p

**Comment by thibaudk** [comment]
Sure, was just testing, can't wait !
Hope the log can be of help anyways.
